name: Testing print-1-10-growing.py

on: [push]

jobs:
  make-testing:
    name: Checking print-1-10-growing.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Running print-1-10-growing.py
        run: |
          diff <(cat <<EOF
          1
          1 2
          1 2 3
          1 2 3 4
          1 2 3 4 5
          1 2 3 4 5 6
          1 2 3 4 5 6 7
          1 2 3 4 5 6 7 8
          1 2 3 4 5 6 7 8 9
          1 2 3 4 5 6 7 8 9 10
          EOF) <(python3 src/print-1-10-growing.py)
        shell: bash
