name: Testing Count

on: [push]

jobs:
  make-testing:
    name: Checking count.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Running count.py
        run: |
          diff <(cat <<EOF
          a: 1
          b: 1
          f: 1
          o: 2
          r: 1
          EOF) <(echo foobar | python3 src/counts.py)
        shell: bash
