name: Testing print-1-10.py

on: [push]

jobs:
  make-testing:
    name: Checking print-1-10.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Running print-1-10.py
        run: |
          diff <(for i in {1..10}; do echo $i; done) \
               <(python3 src/print-1-10.py)
        shell: bash
