name: Testing Hello, World!

on: [push]

jobs:
  make-testing:
    name: Checking hello.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Checking that hello.py returns "Hello, World!"
        run: |
          diff <(echo 'Hello, World!') <(python3 src/hello.py)
        shell: bash
