name: Testing Password

on: [push]

jobs:
  make-testing:
    name: Checking password.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Running password "foobar"
        run: |
          [ `echo False` == `python3 src/password.py foobar` ]
        shell: bash
        
      - name: Running password "Foob@r1"
        run: |
          [ `echo True` == `python3 src/password.py Foob@r1` ]
        shell: bash
