name: Testing Pattern

on: [push]

jobs:
  make-testing:
    name: Checking pattern.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Running pattern.py
        run: |
          diff <(cat <<EOF
          *
          * *
          * * *
          * * * *
          * * * * *
          * * * *
          * * *
          * *
          *
          EOF) <(python3 src/pattern.py)
        shell: bash
