name: Testing "Do you want to stop?"

on: [push]

jobs:
  make-testing:
    name: Checking do-you-want-to-stop.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Checking do-you-want-to-stop.py
        run: |
          diff \
          <(echo -n "Do you want to stop? Do you want to stop? Do you want to stop? "; echo) \
          <(printf "no\nno\nyes\n" | python3 src/do-you-want-to-stop.py; echo)
        shell: bash
